"""add fk items to merchants

Revision ID: 270c9a44fa99
Revises: fd2ee8cd676f
Create Date: 2025-09-28 00:09:55.133038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270c9a44fa99'
down_revision: Union[str, Sequence[str], None] = 'fd2ee8cd676f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_items_merchant_id'), table_name='items')
    op.drop_index(op.f('idx_items_name_trgm'), table_name='items', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_foreign_key(None, 'items', 'merchants', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_merchants_name_trgm'), table_name='merchants', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_merchants_name_trgm'), 'merchants', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_index(op.f('idx_items_name_trgm'), 'items', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_items_merchant_id'), 'items', ['merchant_id'], unique=False)
    # ### end Alembic commands ###
