"""add estimates

Revision ID: 6150ec55e816
Revises: 270c9a44fa99
Create Date: 2025-09-29 01:40:20.335409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6150ec55e816'
down_revision: Union[str, Sequence[str], None] = '270c9a44fa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimates')
    # ### end Alembic commands ###
