"""add item product_category and image_url

Revision ID: a45a7f08b572
Revises: 2907fb901465
Create Date: 2025-09-29 15:12:39.126329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45a7f08b572'
down_revision: Union[str, Sequence[str], None] = '2907fb901465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('product_category', sa.Enum('Beverage', 'Food', 'Snack', 'Condiments', 'Additions', name='item_product_category_enum'), nullable=False))
    op.add_column('items', sa.Column('image_url', sa.String(length=1024), nullable=False))
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'image_url')
    op.drop_column('items', 'product_category')
    # ### end Alembic commands ###
