"""add item product_category and image_url

Revision ID: a45a7f08b572
Revises: 2907fb901465
Create Date: 2025-09-29 15:12:39.126329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a45a7f08b572"
down_revision: Union[str, Sequence[str], None] = "2907fb901465"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

item_product_category_enum = sa.Enum(
    "Beverage",
    "Food",
    "Snack",
    "Condiments",
    "Additions",
    name="item_product_category_enum",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    item_product_category_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "items",
        sa.Column(
            "product_category",
            item_product_category_enum,
            nullable=False,
            server_default="Food",
        ),
    )
    op.add_column(
        "items",
        sa.Column(
            "image_url", sa.String(length=1024), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_check_constraint("ck_items_price_positive", "items", "price >= 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_items_price_positive", "items", type_="check")
    op.drop_column("items", "created_at")
    op.drop_column("items", "image_url")
    op.drop_column("items", "product_category")
    # ### end Alembic commands ###
